data_path: "./data/"
train_data_path: "./data/THUCNews-5_2000/train/"
validate_data_path: "./data/THUCNews-5_2000/validate/"
test_data_path: "./data/THUCNews-5_2000/test/"
input_vocab_path: "./data/input_vocab.txt"
target_vocab_path: "./data/target_vocab.txt"
output_path: "./output/"

frame_class: "pytorch"

seq_length: 10000
num_classes: 5
filter_size: 256
kernel_size: 3
vocab_size: 5000
embedding_size: 50

batch_size: 64
epoch_size: 200
num_save_epoch: 2
learning_rate: 0.01
dropout_keep_prob: 0.5

opt_name: adam
model_class: conv1d