config_name: "tensorflow-cnn"
data_path: "./data/THUCNews-5_2000/"
input_vocab_path: "./data/input_vocab.txt"
target_vocab_path: "./data/target_vocab.txt"

input_max_len: 50000
embedding_size: 1
num_classes: 5

filter_size: 16
kernel_size: 3

batch_size: 64
epoch_size: 200
learning_rate: 0.001

opt_name: adam