data_path: "./data/"
train_data_path: "./data/THUCNews-5_2000/train/"
validate_data_path: "./data/THUCNews-5_2000/validate/"
test_data_path: "./data/THUCNews-5_2000/test/"
input_vocab_path: "./data/input_vocab.txt"
target_vocab_path: "./data/target_vocab.txt"
output_path: "./output/"

input_max_len: 1000
embedding_size: 1
num_classes: 5

filter_size: 128
kernel_size: 5

batch_size: 64
epoch_size: 200
learning_rate: 0.01

opt_name: adam